name: advanced_text_input_formatters_codespark
description: A Flutter package with advanced custom TextInputFormattersâ€”simulate typing, block clipboard, allow only palindromes, enforce naming conventions and more.
version: 0.0.1
homepage: https://github.com/Katayath-Sai-Kiran/advanced_text_input_formatters_codespark
repository: https://github.com/Katayath-Sai-Kiran/advanced_text_input_formatters_codespark

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  # No assets or fonts yet
